apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  storageClassName: do-block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  storageClassName: do-block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
spec:
  storageClassName: do-block-storage
